minecraft-version: 1.20.1-forge-47.3.22

# Формат:
# / на конце - вся директория будет проигнорирована
# * в слове - всё, что содержит слово будет проигнорировано также
# без знаков выше - обозначает единственный файл
update-exclude:
- options.txt
- .nl_password
- config/sodium-settings.json
- patchouli_data.json
- launcher_profiles.json
- usercache.json
- usernamecache.json
- servers.dat_old
- servers.dat.bak
- assets/
- libraries/
- .cache/
- blueprints/
- crash-reports/
- emojiful/
- exposures/
- fancymenu_data/
- hammerlib/
- local/
- logs/
- patchouli_books/
- potionblender/
- saves/
- versions/
- schematics/
- screenshots/
- shaderpacks/
- xaero/
- XaeroWaypoints_BACKUP*/
- .vscode/
