name: Create Client Checksum

on:
  push:
    paths: ["client/**", "generic/**"]
  pull_request:
    types: closed
    paths: ["client/**", "generic/**"]
  workflow_dispatch:

permissions: write-all

jobs:
  hash:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Genereate checksum
        run: |
          find client/ -type f -exec md5sum {} + | awk -F '  ' '{print $2":"$1}' > hash.txt
          find generic/ -type f -exec md5sum {} + | awk -F '  ' '{print $2":"$1}' >> hash.txt
      - name: Commit changes
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Elon Musk"
          git add -f hash.txt
          git commit -m checksum-updated
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
